Edit Date: 11/14/2021

In [1]:
import torch
import torch as nn
import torch.nn.functional as F
import numpy as np

**Tensor**

Tensor is a multi-dimensional matrix containing elements of a single data type.

In [2]:
# Create tensor 
x = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
print(x)

tensor([[1., 4.],
        [2., 1.],
        [3., 5.]])


In [3]:
# Check the first element of tensor
x[0]

tensor([1., 4.])

In [4]:
# Create tensor with 32-bit floating point
x = torch.FloatTensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
x

tensor([[1., 4.],
        [2., 1.],
        [3., 5.]])

In [5]:
# Check tensor type
x.type

<function Tensor.type>

In [6]:
# Check tensor shape
print(x.shape)
print(x.size())

torch.Size([3, 2])
torch.Size([3, 2])


In [7]:
x.storage()

 1.0
 4.0
 2.0
 1.0
 3.0
 5.0
[torch.FloatStorage of size 6]

In [8]:
x = torch.FloatTensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
x_storage = x.storage()
x_storage[1] = 2.0
x

tensor([[1., 2.],
        [2., 1.],
        [3., 5.]])

In [9]:
# Resize
x.view(6)

tensor([1., 2., 2., 1., 3., 5.])

In [10]:
# Resize
x.view(2,3)

tensor([[1., 2., 2.],
        [1., 3., 5.]])

**Basic Math**

Add, substraction,multiplication, mean, and standard deviation

In [11]:
# Add
torch.add(x,x)

tensor([[ 2.,  4.],
        [ 4.,  2.],
        [ 6., 10.]])

In [12]:
# Substraction
torch.sub(x,2)

tensor([[-1.,  0.],
        [ 0., -1.],
        [ 1.,  3.]])

In [13]:
# Multiplication
torch.mul(x,3)

tensor([[ 3.,  6.],
        [ 6.,  3.],
        [ 9., 15.]])

In [14]:
# Division
torch.div(x,2)

tensor([[0.5000, 1.0000],
        [1.0000, 0.5000],
        [1.5000, 2.5000]])

In [15]:
# Mean
torch.mean(x)

tensor(2.3333)

In [16]:
# Standard deviation
torch.std(x)

tensor(1.5055)

**Random Number**

In [17]:
# Create random number
x=torch.rand(5)
x

tensor([0.2599, 0.2174, 0.7679, 0.6186, 0.8832])

In [18]:
x=torch.rand(5,3)
x

tensor([[0.2637, 0.9659, 0.3840],
        [0.2464, 0.3271, 0.8142],
        [0.8217, 0.7599, 0.2721],
        [0.8222, 0.0308, 0.7581],
        [0.9836, 0.4875, 0.6251]])

**Matrix multiplication**

In [19]:
data = [[1,2], [3,4]]
print(np.matmul(data, data)) 

tensor = torch.FloatTensor(data)  # 32-bit floating point
print( torch.mm(tensor, tensor))

[[ 7 10]
 [15 22]]
tensor([[ 7., 10.],
        [15., 22.]])


**Convert tensor and Numpy array**

In [20]:
# Create a numpy array
np_data = np.arange(6).reshape((2, 3))
print(np_data)


# convert numpy to tensor or vise versa
torch_data = torch.from_numpy(np_data)
print(torch_data)

tensor2array = torch_data.numpy()
print(tensor2array)

[[0 1 2]
 [3 4 5]]
tensor([[0, 1, 2],
        [3, 4, 5]])
[[0 1 2]
 [3 4 5]]


** Build Neural Network**

In [21]:
import torch
import torch as nn

In [22]:
# Defining input size, number of neuron, output size and batch size respectively
n_in, n_h, n_out, batch_size = 10, 5, 1, 10

In [23]:
# Create dummy input and target tensors (data)
x = torch.randn(batch_size, n_in)
y = torch.tensor([[1.0], [0.0], [0.0], [1.0], [1.0], [1.0], [0.0], [0.0], [1.0], [1.0]])

In [24]:
x.shape

torch.Size([10, 10])

In [25]:
class Net(torch.nn.Module):
    def __init__(self, n_feature, n_hidden, n_output):
        super(Net, self).__init__()
        self.hidden = torch.nn.Linear(n_feature, n_hidden)   # hidden layer
        self.predict = torch.nn.Linear(n_hidden, n_output)   # output layer

    def forward(self, x):
        x = F.relu(self.hidden(x))      # activation function for hidden layer
        x = nn.sigmoid(self.predict(x))  # activation function for output layer
        return x

model = Net(n_feature=n_in, n_hidden=n_h, n_output=n_out)     # define the network
print(model)  # net architecture

Net(
  (hidden): Linear(in_features=10, out_features=5, bias=True)
  (predict): Linear(in_features=5, out_features=1, bias=True)
)


In [26]:
# Create a model
#model = torch.nn.Sequential(
#        torch.nn.Linear(n_in, n_h),
#        torch.nn.ReLU(),
#        torch.nn.Linear(n_h, n_out),
#        torch.nn.Sigmoid())

In [27]:
# Construct the loss function
criterion = torch.nn.MSELoss()
# Construct the optimizer (Stochastic Gradient Descent in this case)
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

# Gradient Descent
for epoch in range(50):
  # Forward pass: Compute predicted y by passing x to the model
  y_pred = model(x)
  # Compute and print loss
  loss = criterion(y_pred, y)
  print('epoch: ', epoch,' loss: ', loss.item())
  # Zero gradients, perform a backward pass, and update the weights.
  optimizer.zero_grad()
  # perform a backward pass (backpropagation)
  loss.backward()
  # Update the parameters
  optimizer.step()

epoch:  0  loss:  0.2521703243255615
epoch:  1  loss:  0.2520715892314911
epoch:  2  loss:  0.25197315216064453
epoch:  3  loss:  0.251875102519989
epoch:  4  loss:  0.2517774701118469
epoch:  5  loss:  0.2516801357269287
epoch:  6  loss:  0.25158318877220154
epoch:  7  loss:  0.251486599445343
epoch:  8  loss:  0.2513903081417084
epoch:  9  loss:  0.25129440426826477
epoch:  10  loss:  0.25119879841804504
epoch:  11  loss:  0.25110357999801636
epoch:  12  loss:  0.25100865960121155
epoch:  13  loss:  0.2509140968322754
epoch:  14  loss:  0.2508198618888855
epoch:  15  loss:  0.25072595477104187
epoch:  16  loss:  0.2506323754787445
epoch:  17  loss:  0.2505391538143158
epoch:  18  loss:  0.2504462003707886
epoch:  19  loss:  0.25035360455513
epoch:  20  loss:  0.2502613067626953
epoch:  21  loss:  0.2501693367958069
epoch:  22  loss:  0.2500776946544647
epoch:  23  loss:  0.24998638033866882
epoch:  24  loss:  0.2498953640460968
epoch:  25  loss:  0.24980461597442627
epoch:  26  loss:

**Save and load model**

In [28]:
# Save whole net 
torch.save(model, 'model.pkl')

# Save parameters only
torch.save(model.state_dict(), 'model_params.pkl')

In [29]:
# Load whole net 
model = torch.load('model.pkl')

# Save parameters only
model.load_state_dict(torch.load('model_params.pkl'))

<All keys matched successfully>

Reference:
* https://pytorch.org/tutorials/beginner/examples_nn/two_layer_net_nn.html
* https://www.kaggle.com/kanncaa1/pytorch-tutorial-for-deep-learning-lovers